image: ruby:2.4.2
stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: "mongodb://mongo/user_posts"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

.docker_login:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username $DOCKER_REGISTRY_USER --password-stdin

.build:
  before_script:
    - echo 'Extends build'
    - cd reddit
    - bundle install

build_job:
  extends: .build
  stage: build
  script:
    - echo 'Building'

build_image:
  extends: .docker_login
  stage: build
  script:
    - echo 'Building docker image'
    - docker info
    - docker build -t $DOCKER_REGISTRY_USER/reddit .
    - docker push $DOCKER_REGISTRY_USER/reddit

test_unit_job:
  extends: .build
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  extends: .docker_login
  stage: review
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker run -d -p 9292:9292 $DOCKER_REGISTRY_USER/reddit
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - main

staging:
  stage: stage
  when: manual
  script:
    - echo "Deploy"
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: production
    url: http://example.com
