version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    image: ${DOCKER_REGISTRY}/ui:${UI_VERSION}
    ports:
      - ${PUBLIC_PORT}:9292/tcp
    command: "puma -w 2 --debug"
    networks:
      - frontend
  post:
    image: ${DOCKER_REGISTRY}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
  comment:
    image: ${DOCKER_REGISTRY}/comment:${COMMENT_VERSION}
    command: "puma -w 2 --debug"
    networks:
      - backend
      - frontend
  prometheus:
    image: ${DOCKER_REGISTRY}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - "9090:9090"
    volumes:
      - prom_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=1d"
    networks:
      - frontend
      - backend
  node-exporter:
    image: prom/node-exporter:v1.7.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - frontend
      - backend
  mongo-exporter:
    image: percona/mongodb_exporter:0.40.0
    command:
      - '--mongodb.uri=mongodb://mongo_db:27017'
    networks:
      - frontend
      - backend
  blackbox-exporter:
    image: ${DOCKER_REGISTRY}/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION}
    command:
      - '--config.file=/etc/blackboxexporter/config.yml'
    networks:
      - frontend
      - backend

volumes:
  post_db:
  prom_data:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
