---
- name: Prepare host
  hosts: all
  become: true

  tasks:

  - name: Check swap
    command: /sbin/swapon -s
    register: swapon
    changed_when: no

  - name: Disable swap
    command: /sbin/swapoff -a
    when:
      - swapon.stdout
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Disable swap in fstab (Kubeadm requirement)
    lineinfile:
      dest: /etc/fstab
      regexp: swap
      state: absent

  - name: Create an empty file for Kubernetes sysctl params
    copy:
      content: ""
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      force: no

  - name: Configure sysctl params for Kubernetes
    lineinfile:
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      line: "{{ item }}"
    with_items:
      - 'net.ipv4.ip_forward = 1'
      - 'net.bridge.bridge-nf-call-iptables = 1'
      - 'net.bridge.bridge-nf-call-ip6tables = 1'

  - name: Load br_netfilter kernel module
    modprobe:
      name: br_netfilter
      state: present

  - name: Let iptables see bridged traffic.
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
    loop:
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables

  - name: Apt update
    apt:
      upgrade: yes
      update_cache: yes

- name: run ansible galaxy
  local_action: command ansible-galaxy install -r requirements.yml --ignore-errors

- name: Install containerd and k8s
  hosts: all
  become: true
  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes