---
old_versions:
  - docker
  - docker-engine
  - docker.io
  - containerd runc

prepare_install:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

new_versions:
  - docker-ce
  - docker-ce-cli
  - containerd.io

python_modules:
  - python3-pip
  - python3-setuptools
  - virtualenv

python_libs:
  - docker-compose
  - docker

docker_repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

compose_version: "v2.23.3"
compose_binary: docker-compose-linux-aarch64
