---
- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/{{ compose_binary }}"
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x"

- name: Ensure symlink for docker-compose exist
  file:
    path: /usr/local/bin/docker-compose
    src: /usr/bin/docker-compose
    state: link
    force: yes
    follow: false
