---
plugin: yc_compute
folders:
  - b1garuf6j8husgt8i4on
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: key.json
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address

keyed_groups:
  - key: labels['tags']
